
micronaut:
  application:
    name: mqttExample
netty:
  default:
    allocator:
      max-order: 3

---
---
micronaut.server.port: 9090
---

---
datasources:
  default:
    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

---
liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'

---
#This configuration is the default configuration for HiveMQ in localhost
mqtt:
  client:
    client-id: ${random.uuid}
    user-name: admin
    password: hivemq
    server-uri: tcp://localhost:1883

---
micronaut:
  metrics:
    enabled: true
    sensitive: Boolean

---
endpoints:
  prometheus:
    sensitive: false
micronaut:
  metrics:
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M

---
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1

---
graphql:
  graphiql.enabled: true

---
micronaut:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**


---
micronaut:
  router:
    static-resources:
      '*':
        paths:
          - "classpath:static"
        enabled: true
